- name: Install packages
  hosts: mongodb
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.yum:
      name: "{{item.name}}"
      state: "{{item.state}}"
    # List of map
    loop:
    - {name: 'nginx', state: 'absent'}
    - {name: 'postfix', state: 'installed'}
    - {name: 'mailx', state: 'absent'}
    - {name: cyrus-sasl-plain, state: 'installed'}